### ISSUE TITLE
NoMethodError importing lastpass.csv

### ISSUE THREAD

**Issue by darthlukan** [asayers/lastpass-importer#1]
Using Ruby 2.1.7p400 and getting the following error:

```
    $ ./lastpass2pass.rb passes.csv 
    Reading 'passes.csv'...
    114 records found!
    ./lastpass2pass.rb:102:in `block in <main>': undefined method `empty?' for nil:NilClass (NoMethodError)
        from ./lastpass2pass.rb:95:in `each'
    from ./lastpass2pass.rb:95:in `<main>'
```

Is there maybe some dependency that I'm missing in my Ruby installation?

**Comment by asayers** [comment]
Fixed by [password-store:85757e9](http://git.zx2c4.com/password-store/commit/?id=85757e99bff29d6fa663a6b291c9047ccce8c6d3).
